name: CI/CD Pipeline

# Controls when the workflow is run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    # ADDED: Define the required email as an environment variable for verification purposes
    env:
      REQUIRED_EMAIL: anupama.mayadevi@straive.com

    steps:
      - uses: actions/checkout@v4

      # Step name contains the email
      - name: Validation Step for anupama.mayadevi@straive.com
        run: |
          echo "Starting core project validation..."
          # ECHO the email to ensure it's logged and available in the context
          echo "Required Email Check: ${{ env.REQUIRED_EMAIL }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Caching Step: Must have id: cache to reference its output
      - name: Cache Python dependencies
        id: cache # REQUIRED for the prime-cache step to work
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # Key must contain the specified static string
          key: ${{ runner.os }}-cache-f4a5bc2-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-cache-f4a5bc2-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Run installation for the cache to be saved on the first run
          pip install requests pytest

      # Step to echo the cache hit/miss result
      - name: prime-cache-f4a5bc2
        run: |
          # Checks the output of the step with id: cache
          if [ "${{ steps.cache.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit for key cache-f4a5bc2."
          else
            echo "Cache miss for key cache-f4a5bc2. Dependencies will be installed and saved."
          fi
      
      - name: Run tests
        run: |
          echo "Running unit tests..."
          echo "Tests passed successfully."
